[package]
name = "lunavoxel-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = "1.6"
voxel-compression = { path = "../shared/rust/compression" }

[profile.release]
opt-level = 3
lto = true