// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as AccessTypeVariants from './access_type_variants'

// The tagged union or sum type for the algebraic type `AccessType`.
export type AccessType = AccessTypeVariants.None |
  AccessTypeVariants.Inherited |
  AccessTypeVariants.Read |
  AccessTypeVariants.ReadWrite;

// A value with helper functions to construct the type.
export const AccessType = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  None: { tag: "None" } as const,
  Inherited: { tag: "Inherited" } as const,
  Read: { tag: "Read" } as const,
  ReadWrite: { tag: "ReadWrite" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "None", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Inherited", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Read", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "ReadWrite", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: AccessType): void {
      __AlgebraicTypeValue.serializeValue(writer, AccessType.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): AccessType {
      return __AlgebraicTypeValue.deserializeValue(reader, AccessType.getTypeScriptAlgebraicType());
  },

}

export default AccessType;


