// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import * as BlockModificationModeVariants from './block_modification_mode_variants'

// The tagged union or sum type for the algebraic type `BlockModificationMode`.
export type BlockModificationMode = BlockModificationModeVariants.Attach |
  BlockModificationModeVariants.Erase |
  BlockModificationModeVariants.Paint;

let _cached_BlockModificationMode_type_value: __AlgebraicTypeType | null = null;

// A value with helper functions to construct the type.
export const BlockModificationMode = {
  Attach: { tag: "Attach" } as const,
  Erase: { tag: "Erase" } as const,
  Paint: { tag: "Paint" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_BlockModificationMode_type_value) return _cached_BlockModificationMode_type_value;
    _cached_BlockModificationMode_type_value = __AlgebraicTypeValue.Sum({ variants: [] });
    _cached_BlockModificationMode_type_value.value.variants.push(
      { name: "Attach", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Erase", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Paint", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
    );
    return _cached_BlockModificationMode_type_value;
  },
  
  fromValue(value: BlockModificationMode): BlockModificationMode {
    return value;
  },

  safeFromValue(value: BlockModificationMode | undefined): BlockModificationMode | undefined {
    if (value === undefined) return undefined;
    return this.fromValue(value);
  },
};

export default BlockModificationMode;
