// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */

export type Attach = { tag: "Attach" };
export type Erase = { tag: "Erase" };
export type Paint = { tag: "Paint" };
