// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type Chunk = {
  id: string,
  layerId: string,
  minPosX: number,
  minPosY: number,
  minPosZ: number,
  sizeX: number,
  sizeY: number,
  sizeZ: number,
  voxels: Uint8Array,
};
let _cached_Chunk_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Chunk = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Chunk_type_value) return _cached_Chunk_type_value;
    _cached_Chunk_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Chunk_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.String },
      { name: "layerId", algebraicType: __AlgebraicTypeValue.String },
      { name: "minPosX", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "minPosY", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "minPosZ", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "sizeX", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "sizeY", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "sizeZ", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "voxels", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.U8) },
    );
    return _cached_Chunk_type_value;
  },

  serialize(writer: __BinaryWriter, value: Chunk): void {
    __AlgebraicTypeValue.serializeValue(writer, Chunk.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Chunk {
    return __AlgebraicTypeValue.deserializeValue(reader, Chunk.getTypeScriptAlgebraicType());
  },

}

export default Chunk;


