// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { BlockRun as __BlockRun } from "./block_run_type";

export type Chunk = {
  id: string,
  world: string,
  xDim: number,
  yDim: number,
  layer: number,
  blocks: __BlockRun[][][],
};

/**
 * A namespace for generated helper functions.
 */
export namespace Chunk {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createStringType()),
      new ProductTypeElement("world", AlgebraicType.createStringType()),
      new ProductTypeElement("xDim", AlgebraicType.createI32Type()),
      new ProductTypeElement("yDim", AlgebraicType.createI32Type()),
      new ProductTypeElement("layer", AlgebraicType.createI32Type()),
      new ProductTypeElement("blocks", AlgebraicType.createArrayType(AlgebraicType.createArrayType(AlgebraicType.createArrayType(__BlockRun.getTypeScriptAlgebraicType())))),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Chunk): void {
    Chunk.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Chunk {
    return Chunk.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


