// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ColorPalette } from "./color_palette_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `color_palette`.
 *
 * Obtain a handle from the [`colorPalette`] property on [`RemoteTables`],
 * like `ctx.db.colorPalette`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.colorPalette.on_insert(...)`.
 */
export class ColorPaletteTableHandle {
  tableCache: TableCache<ColorPalette>;

  constructor(tableCache: TableCache<ColorPalette>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ColorPalette> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `projectId` unique index on the table `color_palette`,
   * which allows point queries on the field of the same name
   * via the [`ColorPaletteProjectIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.colorPalette.projectId().find(...)`.
   *
   * Get a handle on the `projectId` unique index on the table `color_palette`.
   */
  projectId = {
    // Find the subscribed row whose `projectId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): ColorPalette | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.projectId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ColorPalette) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ColorPalette) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ColorPalette) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ColorPalette) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ColorPalette, newRow: ColorPalette) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ColorPalette, newRow: ColorPalette) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
