// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

export type EraseBlock = {
  world: string,
  x1: number,
  y1: number,
  z1: number,
  x2: number,
  y2: number,
  z2: number,
  isPreview: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace EraseBlock {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("world", AlgebraicType.createStringType()),
      new ProductTypeElement("x1", AlgebraicType.createI32Type()),
      new ProductTypeElement("y1", AlgebraicType.createI32Type()),
      new ProductTypeElement("z1", AlgebraicType.createI32Type()),
      new ProductTypeElement("x2", AlgebraicType.createI32Type()),
      new ProductTypeElement("y2", AlgebraicType.createI32Type()),
      new ProductTypeElement("z2", AlgebraicType.createI32Type()),
      new ProductTypeElement("isPreview", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EraseBlock): void {
    EraseBlock.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): EraseBlock {
    return EraseBlock.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

