// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type Layer = {
  id: string,
  projectId: string,
  xDim: number,
  yDim: number,
  zDim: number,
  index: number,
  voxels: Uint8Array,
  visible: boolean,
  locked: boolean,
  name: string,
};
/**
 * An object for generated helper functions.
 */
export const Layer = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.String},
        { name: "projectId", algebraicType: __AlgebraicTypeValue.String},
        { name: "xDim", algebraicType: __AlgebraicTypeValue.I32},
        { name: "yDim", algebraicType: __AlgebraicTypeValue.I32},
        { name: "zDim", algebraicType: __AlgebraicTypeValue.I32},
        { name: "index", algebraicType: __AlgebraicTypeValue.I32},
        { name: "voxels", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.U8)},
        { name: "visible", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "locked", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "name", algebraicType: __AlgebraicTypeValue.String},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: Layer): void {
    __AlgebraicTypeValue.serializeValue(writer, Layer.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Layer {
    return __AlgebraicTypeValue.deserializeValue(reader, Layer.getTypeScriptAlgebraicType());
  },

}

export default Layer;


