// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type LayerHistoryEntry = {
  id: string,
  projectId: string,
  author: Identity,
  version: bigint,
  isHead: boolean,
  isUndone: boolean,
  layerId: string,
  beforeVoxels: number[],
  diffVoxels: number[],
  isBaseState: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace LayerHistoryEntry {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createStringType()),
      new ProductTypeElement("projectId", AlgebraicType.createStringType()),
      new ProductTypeElement("author", AlgebraicType.createIdentityType()),
      new ProductTypeElement("version", AlgebraicType.createU64Type()),
      new ProductTypeElement("isHead", AlgebraicType.createBoolType()),
      new ProductTypeElement("isUndone", AlgebraicType.createBoolType()),
      new ProductTypeElement("layerId", AlgebraicType.createStringType()),
      new ProductTypeElement("beforeVoxels", AlgebraicType.createArrayType(AlgebraicType.createI16Type())),
      new ProductTypeElement("diffVoxels", AlgebraicType.createArrayType(AlgebraicType.createI16Type())),
      new ProductTypeElement("isBaseState", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: LayerHistoryEntry): void {
    LayerHistoryEntry.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): LayerHistoryEntry {
    return LayerHistoryEntry.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


