// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

import { Vector3 } from "./vector_3_type";
// Mark import as potentially unused
declare type __keep_Vector3 = Vector3;

export type MagicSelect = {
  projectId: string,
  layerIndex: number,
  position: Vector3,
};
/**
 * An object for generated helper functions.
 */
export const MagicSelect = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "projectId", algebraicType: __AlgebraicTypeValue.String},
        { name: "layerIndex", algebraicType: __AlgebraicTypeValue.I32},
        { name: "position", algebraicType: Vector3.getTypeScriptAlgebraicType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: MagicSelect): void {
    __AlgebraicTypeValue.serializeValue(writer, MagicSelect.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): MagicSelect {
    return __AlgebraicTypeValue.deserializeValue(reader, MagicSelect.getTypeScriptAlgebraicType());
  },

}

export default MagicSelect;

