// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

import { Vector3 } from "./vector_3_type";
// Mark import as potentially unused
declare type __keep_Vector3 = Vector3;
import { BlockModificationMode } from "./block_modification_mode_type";
// Mark import as potentially unused
declare type __keep_BlockModificationMode = BlockModificationMode;

export type ModifyBlocks = {
  projectId: string,
  mode: BlockModificationMode,
  minPos: Vector3,
  maxPos: Vector3,
  compressedVoxelData: Uint8Array,
  layerIndex: number,
};
let _cached_ModifyBlocks_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const ModifyBlocks = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_ModifyBlocks_type_value) return _cached_ModifyBlocks_type_value;
    _cached_ModifyBlocks_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_ModifyBlocks_type_value.value.elements.push(
      { name: "projectId", algebraicType: __AlgebraicTypeValue.String },
      { name: "mode", algebraicType: BlockModificationMode.getTypeScriptAlgebraicType() },
      { name: "minPos", algebraicType: Vector3.getTypeScriptAlgebraicType() },
      { name: "maxPos", algebraicType: Vector3.getTypeScriptAlgebraicType() },
      { name: "compressedVoxelData", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.U8) },
      { name: "layerIndex", algebraicType: __AlgebraicTypeValue.I32 },
    );
    return _cached_ModifyBlocks_type_value;
  },

  serialize(writer: __BinaryWriter, value: ModifyBlocks): void {
    __AlgebraicTypeValue.serializeValue(writer, ModifyBlocks.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ModifyBlocks {
    return __AlgebraicTypeValue.deserializeValue(reader, ModifyBlocks.getTypeScriptAlgebraicType());
  },

}

export default ModifyBlocks;

