// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

import { ToolType } from "./tool_type_type";
// Mark import as potentially unused
declare type __keep_ToolType = ToolType;
import { Vector3 } from "./vector_3_type";
// Mark import as potentially unused
declare type __keep_Vector3 = Vector3;

export type ModifyBlockRect = {
  projectId: string,
  mode: ToolType,
  type: number,
  start: Vector3,
  end: Vector3,
  rotation: number,
  layerIndex: number,
};
/**
 * An object for generated helper functions.
 */
export const ModifyBlockRect = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "projectId", algebraicType: __AlgebraicTypeValue.String},
        { name: "mode", algebraicType: ToolType.getTypeScriptAlgebraicType()},
        { name: "type", algebraicType: __AlgebraicTypeValue.U32},
        { name: "start", algebraicType: Vector3.getTypeScriptAlgebraicType()},
        { name: "end", algebraicType: Vector3.getTypeScriptAlgebraicType()},
        { name: "rotation", algebraicType: __AlgebraicTypeValue.U32},
        { name: "layerIndex", algebraicType: __AlgebraicTypeValue.I32},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ModifyBlockRect): void {
    __AlgebraicTypeValue.serializeValue(writer, ModifyBlockRect.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ModifyBlockRect {
    return __AlgebraicTypeValue.deserializeValue(reader, ModifyBlockRect.getTypeScriptAlgebraicType());
  },

}

export default ModifyBlockRect;

