// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { Vector3Float } from "./vector_3_float_type";
// Mark import as potentially unused
declare type __keep_Vector3Float = Vector3Float;


export type PlayerCursor = {
  id: string,
  projectId: string,
  displayName: string,
  player: __Identity,
  position: Vector3Float | undefined,
  normal: Vector3Float | undefined,
  lastUpdated: __Timestamp,
};
/**
 * An object for generated helper functions.
 */
export const PlayerCursor = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.String},
        { name: "projectId", algebraicType: __AlgebraicTypeValue.String},
        { name: "displayName", algebraicType: __AlgebraicTypeValue.String},
        { name: "player", algebraicType: __AlgebraicTypeValue.createIdentityType()},
        { name: "position", algebraicType: __AlgebraicTypeValue.createOptionType(Vector3Float.getTypeScriptAlgebraicType())},
        { name: "normal", algebraicType: __AlgebraicTypeValue.createOptionType(Vector3Float.getTypeScriptAlgebraicType())},
        { name: "lastUpdated", algebraicType: __AlgebraicTypeValue.createTimestampType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: PlayerCursor): void {
    __AlgebraicTypeValue.serializeValue(writer, PlayerCursor.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PlayerCursor {
    return __AlgebraicTypeValue.deserializeValue(reader, PlayerCursor.getTypeScriptAlgebraicType());
  },

}

export default PlayerCursor;


