// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { AccessType as __AccessType } from "./access_type_type";
import { Vector3 as __Vector3 } from "./vector_3_type";

export type Project = {
  id: string,
  name: string,
  dimensions: __Vector3,
  owner: Identity,
  lastVisited: Timestamp,
  publicAccess: __AccessType,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Project {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createStringType()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("dimensions", __Vector3.getTypeScriptAlgebraicType()),
      new ProductTypeElement("owner", AlgebraicType.createIdentityType()),
      new ProductTypeElement("lastVisited", AlgebraicType.createTimestampType()),
      new ProductTypeElement("publicAccess", __AccessType.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Project): void {
    Project.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Project {
    return Project.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


