// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { ProjectBlocks } from "./project_blocks_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `project_blocks`.
 *
 * Obtain a handle from the [`projectBlocks`] property on [`RemoteTables`],
 * like `ctx.db.projectBlocks`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.projectBlocks.on_insert(...)`.
 */
export class ProjectBlocksTableHandle {
  tableCache: TableCache<ProjectBlocks>;

  constructor(tableCache: TableCache<ProjectBlocks>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ProjectBlocks> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `projectId` unique index on the table `project_blocks`,
   * which allows point queries on the field of the same name
   * via the [`ProjectBlocksProjectIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.projectBlocks.projectId().find(...)`.
   *
   * Get a handle on the `projectId` unique index on the table `project_blocks`.
   */
  projectId = {
    // Find the subscribed row whose `projectId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): ProjectBlocks | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.projectId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ProjectBlocks) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ProjectBlocks) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ProjectBlocks) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ProjectBlocks) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ProjectBlocks, newRow: ProjectBlocks) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ProjectBlocks, newRow: ProjectBlocks) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
