// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { Vector3 } from "./vector_3_type";

export type Selection = {
  id: string,
  identity: __Identity,
  projectId: string,
  layer: number,
  minPos: Vector3,
  maxPos: Vector3,
  selectionData: Uint8Array,
};
let _cached_Selection_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Selection = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Selection_type_value) return _cached_Selection_type_value;
    _cached_Selection_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Selection_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.String },
      { name: "identity", algebraicType: __AlgebraicTypeValue.createIdentityType() },
      { name: "projectId", algebraicType: __AlgebraicTypeValue.String },
      { name: "layer", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "minPos", algebraicType: Vector3.getTypeScriptAlgebraicType() },
      { name: "maxPos", algebraicType: Vector3.getTypeScriptAlgebraicType() },
      { name: "selectionData", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.U8) },
    );
    return _cached_Selection_type_value;
  },

  serialize(writer: __BinaryWriter, value: Selection): void {
    __AlgebraicTypeValue.serializeValue(writer, Selection.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Selection {
    return __AlgebraicTypeValue.deserializeValue(reader, Selection.getTypeScriptAlgebraicType());
  },

}

export default Selection;


