// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type UpdateBlock = {
  projectId: string,
  index: number,
  faceColors: number[],
};
/**
 * An object for generated helper functions.
 */
export const UpdateBlock = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "projectId", algebraicType: __AlgebraicTypeValue.String},
        { name: "index", algebraicType: __AlgebraicTypeValue.I32},
        { name: "faceColors", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: UpdateBlock): void {
    __AlgebraicTypeValue.serializeValue(writer, UpdateBlock.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): UpdateBlock {
    return __AlgebraicTypeValue.deserializeValue(reader, UpdateBlock.getTypeScriptAlgebraicType());
  },

}

export default UpdateBlock;

