// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

import { Vector3Float as __Vector3Float } from "./vector_3_float_type";

export type UpdateCursorPos = {
  projectId: string,
  identity: Identity,
  pos: __Vector3Float | undefined,
  normal: __Vector3Float | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace UpdateCursorPos {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("projectId", AlgebraicType.createStringType()),
      new ProductTypeElement("identity", AlgebraicType.createIdentityType()),
      new ProductTypeElement("pos", AlgebraicType.createOptionType(__Vector3Float.getTypeScriptAlgebraicType())),
      new ProductTypeElement("normal", AlgebraicType.createOptionType(__Vector3Float.getTypeScriptAlgebraicType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: UpdateCursorPos): void {
    UpdateCursorPos.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): UpdateCursorPos {
    return UpdateCursorPos.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

